import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineCog6Tooth,
  HiOutlineSparkles,
  HiOutlineCpuChip,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiListChecksDuotone,
  PiDatabaseDuotone,
  PiBrain,
  PiLockDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiOpenai,
  SiMeta,
  SiApple,
  SiGoogle,
  SiAnthropic,
  SiVolkswagen,
  SiBmw,
  SiPorsche,
  SiMercedes,
  SiAudi,
  SiSkoda,
  SiOpel,
  SiMan,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaStar, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  react: SiReact,
  "project-management": PiListChecksDuotone,
  star: FaStar,
  settings: HiOutlineCog6Tooth,
  zap: HiOutlineSparkles,
  database: PiDatabaseDuotone,
  cpu: HiOutlineCpuChip,
  brain: PiBrain,
  userLock: PiLockDuotone,
  openai: SiOpenai,
  meta: SiMeta,
  apple: SiApple,
  google: SiGoogle,
  anthropic: SiAnthropic,
  volkswagen: SiVolkswagen,
  bmw: SiBmw,
  porsche: SiPorsche,
  mercedes: SiMercedes,
  audi: SiAudi,
  skoda: SiSkoda,
  opel: SiOpel,
  man: SiMan,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
